## Ejemplo 6: Automatizando peticiones

### 1. Objetivos:
    - Usar todo lo que aprendimos para automatizar peticiones al API
    - Guardar nuestros resultados en un archivo tipo .csv
 
---
    
### 2. Desarrollo:

Veamos cómo usar todo lo que aprendimos para automatizar el proceso de realizar múltiples peticiones a la API, reunirlas en un `DataFrame` y guardarlo en un .csv:

In [8]:
import pandas as pd
import requests
import time

In [9]:
endpoint = 'https://api.nasa.gov/neo/rest/v1/neo/browse/'
payload = {'api_key': 'tu_api_key_va_aqui'}

In [10]:
dict_datos = {}

for i in range(0, 10):
    
    try:
        time.sleep(5)
        r = requests.get(endpoint, params=payload, timeout=5)

        if r.status_code == 200:
            json = r.json()

            data = json['near_earth_objects']
            dict_datos[i] = data

            new_link = json['links']['next']
            endpoint = new_link
    except:
        continue

In [11]:
for key in dict_datos:
    normalized = pd.json_normalize(dict_datos[key])
    df = pd.DataFrame.from_dict(normalized)
    dict_datos[key] = df

In [12]:
lista_de_dataframes = []

for key in dict_datos:
    lista_de_dataframes.append(dict_datos[key])

In [13]:
df_completo = pd.concat(lista_de_dataframes, axis=0).reset_index(drop=True)

In [14]:
df_completo

,id,neo_reference_id,name,designation,nasa_jpl_url,absolute_magnitude_h,is_potentially_hazardous_asteroid,close_approach_data,is_sentry_object,links.self,...,orbital_data.aphelion_distance,orbital_data.perihelion_time,orbital_data.mean_anomaly,orbital_data.mean_motion,orbital_data.equinox,orbital_data.orbit_class.orbit_class_type,orbital_data.orbit_class.orbit_class_description,orbital_data.orbit_class.orbit_class_range,name_limited,orbital_data.orbit_class
0,2021277,2021277,21277 (1996 TO5),21277,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2021277,16.1,False,"[{'close_approach_date': '1945-06-07', 'close_...",False,http://www.neowsapp.com/rest/v1/neo/2021277?ap...,...,3.613831997036431,2458492.539296262276,136.646856932786,.2690106851323308,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN,NaN
1,2162038,2162038,162038 (1996 DH),162038,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2162038,16.6,False,[],False,http://www.neowsapp.com/rest/v1/neo/2162038?ap...,...,2.025868476312066,2459176.565253751041,273.1861379061811,.493077766590875,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN,NaN
2,2189058,2189058,189058 (2000 UT16),189058,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2189058,16.5,False,[],False,http://www.neowsapp.com/rest/v1/neo/2189058?ap...,...,3.884205451986184,2459278.734090121480,293.4095292372738,.2393325373380815,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN,NaN
3,2276274,2276274,276274 (2002 SS41),276274,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2276274,17.2,False,[],False,http://www.neowsapp.com/rest/v1/neo/2276274?ap...,...,2.910206355077709,2459093.016756074428,330.1368350661496,.322786554576405,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN,NaN
4,2322913,2322913,322913 (2002 CM1),322913,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=2322913,16.7,False,[],False,http://www.neowsapp.com/rest/v1/neo/2322913?ap...,...,3.361558630853122,2458482.209254870466,146.5048635106909,.2826692640905165,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,3879534,3879534,(2019 UO4),2019 UO4,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=3879534,24.7,False,"[{'close_approach_date': '2019-10-16', 'close_...",False,http://www.neowsapp.com/rest/v1/neo/3879534?ap...,...,2.356145063887216,2458734.942685330012,20.2230372412315,.4538657096149674,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,NaN,NaN
196,3892768,3892768,(2019 VT4),2019 VT4,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=3892768,24.4,False,"[{'close_approach_date': '2019-11-21', 'close_...",False,http://www.neowsapp.com/rest/v1/neo/3892768?ap...,...,1.695958399821732,2458817.861061683347,344.1161203782057,.6025508309412494,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN,NaN
197,3593352,3593352,(2010 GE69),2010 GE69,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=3593352,NaN,False,[],False,http://www.neowsapp.com/rest/v1/neo/3593352?ap...,...,2.252320635427747,2454865.269039801145,182.0553238983248,.4192591974900937,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN,NaN
198,3943343,3943343,(2019 YS1),2019 YS1,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=3943343,25.7,False,"[{'close_approach_date': '2019-12-14', 'close_...",False,http://www.neowsapp.com/rest/v1/neo/3943343?ap...,...,2.873109473373824,2458816.635743913359,8.354869418916564,.3654118195342511,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,NaN,NaN
199,3943345,3943345,(2019 YU1),2019 YU1,http://ssd.jpl.nasa.gov/sbdb.cgi?sstr=3943345,24.3,False,"[{'close_approach_date': '2019-12-20', 'close_...",False,http://www.neowsapp.com/rest/v1/neo/3943345?ap...,...,1.413689789640154,2458767.240822438503,58.45753614966404,.8203509800434466,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,NaN,NaN

In [15]:
df_completo.to_csv('../../Datasets/near_earth_objects-raw.csv')

¡Listo! Ya tenemos nuestro dataset para procesar en la siguiente sesión. En este último reto vas a implementar tú mismo este proceso, con la única diferencia de que vas a pedir de la página 10 a la 110. ¡Mucha suerte!