## Ejemplo 6: Sort

### 1. Objetivos:
    - Aprender a usar `sort_values` para reordenar nuestros datos
 
---
    
### 2. Desarrollo:

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('../../Datasets/new_york_times_bestsellers-dirty.csv', index_col=0)

df.head()

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
0,http://www.amazon.com/The-Host-Novel-Stephenie...,Stephenie Meyer,Descr: Aliens have taken control of the minds ...,"Little, Brown",THE HOST,5b4aa4ead3089013507db18c,2008-05-24 00:00:00,1212883200000,2,1,3,25.99
1,http://www.amazon.com/Love-Youre-With-Emily-Gi...,Emily Giffin,Descr: A woman's happy marriage is shaken when...,St. Martin's,LOVE THE ONE YOU'RE WITH,5b4aa4ead3089013507db18d,2008-05-24 00:00:00,1212883200000,3,2,2,24.95
2,http://www.amazon.com/The-Front-Garano-Patrici...,Patricia Cornwell,Descr: A Massachusetts state investigator and ...,Putnam,THE FRONT,5b4aa4ead3089013507db18e,2008-05-24 00:00:00,1212883200000,4,0,1,22.95
3,http://www.amazon.com/Snuff-Chuck-Palahniuk/dp...,Chuck Palahniuk,Descr: An aging porn queens aims to cap her ca...,Doubleday,SNUFF,5b4aa4ead3089013507db18f,2008-05-24 00:00:00,1212883200000,5,0,1,24.95
5,http://www.amazon.com/Phantom-Prey-John-Sandfo...,John Sandford,Descr: The Minneapolis detective Lucas Davenpo...,Putnam,PHANTOM PREY,5b4aa4ead3089013507db191,2008-05-24 00:00:00,1212883200000,7,4,3,26.95

Por ejemplo, queremos ordenar nuestras entradas empezando por el libro de mayor precio hasta el libro de menor precio. Esto es un ordenamiento usando la columna 'price.numberDouble' de manera descendente. Esto se har√≠a de la siguiente manera:

In [6]:
df.sort_values('price.numberDouble', ascending=False)

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
2264,http://www.amazon.com/1Q84-Haruki-Murakami-ebo...,Haruki Murakami,"Descr: In 1980s Tokyo, a woman who punishes pe...",Knopf,1Q84,5b4aa4ead3089013507dbff5,2011-12-03 00:00:00,1324166400000,11,12,6,30.50
2255,http://www.amazon.com/1Q84-Haruki-Murakami-ebo...,Haruki Murakami,"Descr: In 1980s Tokyo, a woman who punishes pe...",Knopf,1Q84,5b4aa4ead3089013507dbfe2,2011-11-26 00:00:00,1323561600000,12,10,5,30.50
2276,http://www.amazon.com/1Q84-Haruki-Murakami-ebo...,Haruki Murakami,"Descr: In 1980s Tokyo, a woman who punishes pe...",Knopf,1Q84,5b4aa4ead3089013507dc00b,2011-12-10 00:00:00,1324771200000,13,11,7,30.50
2287,http://www.amazon.com/1Q84-Haruki-Murakami-ebo...,Haruki Murakami,"Descr: In 1980s Tokyo, a woman who punishes pe...",Knopf,1Q84,5b4aa4ead3089013507dc01e,2011-12-17 00:00:00,1325376000000,12,13,8,30.50
2232,http://www.amazon.com/1Q84-Haruki-Murakami-ebo...,Haruki Murakami,"Descr: In 1980s Tokyo, a woman who punishes pe...",Knopf,1Q84,5b4aa4ead3089013507dbfb4,2011-11-12 00:00:00,1322352000000,6,6,3,30.50
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,http://www.amazon.com/1225-Christmas-Tree-Lane...,Debbie Macomber,Descr: Puppies and an ex-husband loom large in...,Mira,1225 CHRISTMAS TREE LANE,5b4aa4ead3089013507dbf81,2011-10-22 00:00:00,1320537600000,15,10,4,16.95
237,http://www.amazon.com/Cedar-Cove-Christmas-Deb...,Debbie Macomber,Descr: A pregnant woman shows up in Cedar Cove...,Mira,A CEDAR COVE CHRISTMAS,5b4aa4ead3089013507db30d,2008-10-04 00:00:00,1224374400000,7,0,1,16.95
1343,http://www.amazon.com/Blockade-Billy-Stephen-K...,Stephen King,"Descr: A tale about the dark side of baseball,...",Scribner,BLOCKADE BILLY,5b4aa4ead3089013507db9f6,2010-06-13 00:00:00,1277596800000,16,13,3,14.99
1310,http://www.amazon.com/Blockade-Billy-Stephen-K...,Stephen King,"Descr: A tale about the dark side of baseball,...",Simon & Schuster,BLOCKADE BILLY,5b4aa4ead3089013507db9c7,2010-05-30 00:00:00,1276387200000,9,0,1,14.99
1328,http://www.amazon.com/Blockade-Billy-Stephen-K...,Stephen King,"Descr: A tale about the dark side of baseball,...",Scribner,BLOCKADE BILLY,5b4aa4ead3089013507db9df,2010-06-06 00:00:00,1276992000000,13,9,2,14.99

Si convertimos 'published_date.numberLong' a `datetime`, podemos tambi√©n ordenar desde la publicaci√≥n m√°s antigua hasta la publicaci√≥n m√°s reciente:

In [7]:
df['published_date.numberLong'] = pd.to_datetime(df['published_date.numberLong'], unit='ms')

In [8]:
df.sort_values('published_date.numberLong', ascending=True)

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
0,http://www.amazon.com/The-Host-Novel-Stephenie...,Stephenie Meyer,Descr: Aliens have taken control of the minds ...,"Little, Brown",THE HOST,5b4aa4ead3089013507db18c,2008-05-24 00:00:00,2008-06-08,2,1,3,25.99
1,http://www.amazon.com/Love-Youre-With-Emily-Gi...,Emily Giffin,Descr: A woman's happy marriage is shaken when...,St. Martin's,LOVE THE ONE YOU'RE WITH,5b4aa4ead3089013507db18d,2008-05-24 00:00:00,2008-06-08,3,2,2,24.95
2,http://www.amazon.com/The-Front-Garano-Patrici...,Patricia Cornwell,Descr: A Massachusetts state investigator and ...,Putnam,THE FRONT,5b4aa4ead3089013507db18e,2008-05-24 00:00:00,2008-06-08,4,0,1,22.95
3,http://www.amazon.com/Snuff-Chuck-Palahniuk/dp...,Chuck Palahniuk,Descr: An aging porn queens aims to cap her ca...,Doubleday,SNUFF,5b4aa4ead3089013507db18f,2008-05-24 00:00:00,2008-06-08,5,0,1,24.95
5,http://www.amazon.com/Phantom-Prey-John-Sandfo...,John Sandford,Descr: The Minneapolis detective Lucas Davenpo...,Putnam,PHANTOM PREY,5b4aa4ead3089013507db191,2008-05-24 00:00:00,2008-06-08,7,4,3,26.95
...,...,...,...,...,...,...,...,...,...,...,...,...
3026,http://www.amazon.com/Dont-Go-Lisa-Scottoline-...,Lisa Scottoline,Descr: An Army doctor returns from Afghanistan...,St. Martin's,DON'T GO,5b4aa4ead3089013507dc591,2013-04-20 00:00:00,2013-05-05,7,2,2,27.99
3027,http://www.amazon.com/Unintended-Consequences-...,Stuart Woods,Descr: The New York lawyer Stone Barrington di...,Putnam,UNINTENDED CONSEQUENCES,5b4aa4ead3089013507dc592,2013-04-20 00:00:00,2013-05-05,8,4,2,26.95
3028,http://www.amazon.com/Six-Years-Harlan-Coben/d...,Harlan Coben,Descr: Jake Fisher discovers that neither the ...,Dutton,SIX YEARS,5b4aa4ead3089013507dc593,2013-04-20 00:00:00,2013-05-05,9,8,5,27.95
3029,http://www.amazon.com/The-Interestings-Novel-M...,Meg Wolitzer,Descr: Six friends meet in the 1970s at a summ...,Riverhead,THE INTERESTINGS,5b4aa4ead3089013507dc595,2013-04-20 00:00:00,2013-05-05,11,11,2,27.95
3031,http://www.amazon.com/The-Storyteller-Jodi-Pic...,Jodi Picoult,Descr: A New Hampshire baker finds herself in ...,Emily Bestler/Atria,THE STORYTELLER,5b4aa4ead3089013507dc598,2013-04-20 00:00:00,2013-05-05,14,10,8,28.99

Por ejemplo, podr√≠amos primero filtrar para s√≥lo tener los libros de la editorial que tiene m√°s libros como 'best sellers' y despu√©s ordenarlos del que pas√≥ m√°s d√≠as en la lista de 'best sellers' al que pas√≥ menos d√≠as en la lista:

In [10]:
df['publisher'].value_counts()

Putnam                                     267
Grand Central                              227
Knopf                                      216
Little, Brown                              211
Doubleday                                  153
                                          ...
Daw                                          1
Harper Voyager/HarperCollins Publishers      1
Morrow/HarperCollins Publishers              1
Viking,                                      1
Twelve                                       1
Name: publisher, Length: 69, dtype: int64

In [11]:
df_putnam = df[df['publisher'] == 'Putnam']

In [12]:
df_putnam.sort_values('weeks_on_list.numberInt', ascending=False)

,amazon_product_url,author,description,publisher,title,oid,bestsellers_date.numberLong,published_date.numberLong,rank.numberInt,rank_last_week.numberInt,weeks_on_list.numberInt,price.numberDouble
470,http://www.amazon.com/Scarpetta-Kay-Patricia-C...,Patricia Cornwell,Descr: The forensic pathologist Kay Scarpetta ...,Putnam,SCARPETTA,5b4aa4ead3089013507db491,2009-02-14 00:00:00,2009-03-01,15,14,11,27.95
455,http://www.amazon.com/Scarpetta-Kay-Patricia-C...,Patricia Cornwell,Descr: The forensic pathologist Kay Scarpetta ...,Putnam,SCARPETTA,5b4aa4ead3089013507db47c,2009-02-07 00:00:00,2009-02-22,14,12,10,27.95
438,http://www.amazon.com/Scarpetta-Kay-Patricia-C...,Patricia Cornwell,Descr: The forensic pathologist Kay Scarpetta ...,Putnam,SCARPETTA,5b4aa4ead3089013507db466,2009-01-31 00:00:00,2009-02-15,12,6,9,27.95
421,http://www.amazon.com/Scarpetta-Kay-Patricia-C...,Patricia Cornwell,Descr: The forensic pathologist Kay Scarpetta ...,Putnam,SCARPETTA,5b4aa4ead3089013507db44c,2009-01-24 00:00:00,2009-02-08,6,6,8,27.95
1072,http://www.amazon.com/U-Undertow-Kinsey-Millho...,Sue Grafton,Descr: Kinsey Millhone investigates the case o...,Putnam,U IS FOR UNDERTOW,5b4aa4ead3089013507db84e,2010-01-17 00:00:00,2010-01-31,12,11,7,27.95
...,...,...,...,...,...,...,...,...,...,...,...,...
925,http://www.amazon.com/The-Scarpetta-Factor-Nov...,Patricia Cornwell,Descr: Apparent threats on Kay Scarpetta‚Äôs li...,Putnam,THE SCARPETTA FACTOR,5b4aa4ead3089013507db754,2009-10-24 00:00:00,2009-11-08,2,0,1,27.95
2150,http://www.amazon.com/Son-Stone-Barrington-Nov...,Stuart Woods,Descr: The New York lawyer Stone Barrington ge...,Putnam,SON OF STONE,5b4aa4ead3089013507dbf27,2011-09-24 00:00:00,2011-10-09,5,0,1,26.95
2137,http://www.amazon.com/Killing-Blues-Jesse-Ston...,Michael Brandman,"Descr: Jesse Stone, the chief of police in Par...",Putnam,ROBERT B. PARKER‚ÄôS KILLING THE BLUES,5b4aa4ead3089013507dbf13,2011-09-17 00:00:00,2011-10-02,5,0,1,25.95
993,http://www.amazon.com/U-Undertow-Kinsey-Millho...,Sue Grafton,Descr: Kinsey Millhone investigates the case o...,Putnam,U IS FOR UNDERTOW,5b4aa4ead3089013507db7cb,2009-12-05 00:00:00,2009-12-20,1,0,1,27.95
2,http://www.amazon.com/The-Front-Garano-Patrici...,Patricia Cornwell,Descr: A Massachusetts state investigator and ...,Putnam,THE FRONT,5b4aa4ead3089013507db18e,2008-05-24 00:00:00,2008-06-08,4,0,1,22.95